
language: java
sudo: false
addons:
  postgresql: 9.3
services:
  - couchdb
  - rabbitmq
before_script:
      - psql -c "ALTER USER postgres WITH PASSWORD 'password'" -U postgres
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn test
<<<<<<< HEAD

=======
after_success:
  - mvn clean cobertura:cobertura coveralls:report
>>>>>>> 27e8f00104d97c36c47388d2b5eb221a9001dcc7
